export const REDUCER_NAME = 'APP'

// ActionTypes
export const CHECK_WORKING = `${REDUCER_NAME}/CHECK_WORKiNG`
export const LIST_CALCULATOR = `${REDUCER_NAME}/LIST_CALCULATOR`
export const CALCULATE_CALCULATOR = `${REDUCER_NAME}/CALCULATE_CALCULATOR`
export const ADD_CALCULATOR = `${REDUCER_NAME}/ADD_CALCULATOR`
export const UPDATE_CALCULATOR = `${REDUCER_NAME}/UPDATE_CALCULATOR`
export const REMOVE_CALCULATOR = `${REDUCER_NAME}/REMOVE_CALCULATOR`
