export const REDUCER_NAME = 'APP'

// ActionTypes
export const CHECK_WORKING = `${REDUCER_NAME}/CHECK_WORKiNG`
export const LIST_CALCULATOR = `${REDUCER_NAME}/LIST_CALCULATOR`
export const CALCULATE_CALCULATOR = `${REDUCER_NAME}/CALCULATE_CALCULATOR`
export const ADD_CALCULATOR = `${REDUCER_NAME}/ADD_CALCULATOR`
export const UPDATE_CALCULATOR = `${REDUCER_NAME}/UPDATE_CALCULATOR`
export const REMOVE_CALCULATOR = `${REDUCER_NAME}/REMOVE_CALCULATOR`
export const REMOVE_CALCULATOR_WORK = `${REDUCER_NAME}/REMOVE_CALCULATOR_WORK`
export const ADD_CALCULATOR_WORK = `${REDUCER_NAME}/ADD_CALCULATOR_WORK`
export const UPDATE_CALCULATOR_WORK = `${REDUCER_NAME}/UPDATE_CALCULATOR_WORK`

export const ADD_PERCENTAGE_CALCULATOR = `${REDUCER_NAME}/ADD_PERCENTAGE_CALCULATOR`
export const REMOVE_PERCENTAGE_CALCULATOR = `${REDUCER_NAME}/REMOVE_PERCENTAGE_CALCULATOR`
export const UPDATE_PERCENTAGE_CALCULATOR = `${REDUCER_NAME}/UPDATE_PERCENTAGE_CALCULATOR`

export const SET_COMPLEXITY = `${REDUCER_NAME}/SET_COMPLEXITY`
export const UPDATE_TAG_COUNT = `${REDUCER_NAME}/UPDATE_TAG_COUNT`
